/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.view.receptionist;

/**
 *
 * @author domin
 */
public class ReceptionistAppointmentView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReceptionistAppointmentView
     */
    public ReceptionistAppointmentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receptionistAppointmentViewAddButton = new javax.swing.JButton();
        receptionistAppointmentViewDeleteButton = new javax.swing.JButton();
        receptionistAppointmentViewUpdateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receptionistAppointmentViewTable = new javax.swing.JTable();
        receptionistAppointmentViewPatientIdLable = new javax.swing.JLabel();
        receptionistAppointmentViewPatientNameLabel = new javax.swing.JLabel();
        receptionistAppointmentViewPatientSurnameLabel = new javax.swing.JLabel();
        receptionistAppointmentViewPatientIdTextField = new javax.swing.JTextField();
        receptionistAppointmentViewPatientNameTextField = new javax.swing.JTextField();
        receptionistAppointmentViewPatientSurnameTextLabel = new javax.swing.JTextField();
        receptionistAppointmentViewDoctorIdLabel = new javax.swing.JLabel();
        receptionistAppointmentViewDoctorIdTextField = new javax.swing.JTextField();
        receptionistAppointmentViewDoctorNameTextField = new javax.swing.JTextField();
        receptionistAppointmentViewDoctorNameLabel = new javax.swing.JLabel();
        receptionistAppointmentViewDoctorSurnameLabel = new javax.swing.JLabel();
        receptionistAppointmentViewDoctorSurnameTextField = new javax.swing.JTextField();
        receptionistAppointmentViewDoctorDepartmentLabel = new javax.swing.JLabel();
        receptionistAppointmentViewDoctorDepartmentTextField = new javax.swing.JTextField();
        receptionistAppointmentViewAppointmentDateLabel = new javax.swing.JLabel();
        receptionistAppointmentViewAppointmentDateTextField = new javax.swing.JTextField();

        setTitle("Appointment");

        receptionistAppointmentViewAddButton.setText("Add");
        receptionistAppointmentViewAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receptionistAppointmentViewAddButtonActionPerformed(evt);
            }
        });

        receptionistAppointmentViewDeleteButton.setText("Delete");

        receptionistAppointmentViewUpdateButton.setText("Update");

        receptionistAppointmentViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Patient Surname", "Doctor ID", "Doctor Name", "Doctor Surname", "Doctor Department", "Appointment Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(receptionistAppointmentViewTable);

        receptionistAppointmentViewPatientIdLable.setText("Patient ID                 :");

        receptionistAppointmentViewPatientNameLabel.setText("Patient Name            :");

        receptionistAppointmentViewPatientSurnameLabel.setText("Patient Surname       :");

        receptionistAppointmentViewDoctorIdLabel.setText("Doctor ID                 :");

        receptionistAppointmentViewDoctorNameLabel.setText("Doctor Name            :");

        receptionistAppointmentViewDoctorSurnameLabel.setText("Doctor Surname       :");

        receptionistAppointmentViewDoctorDepartmentLabel.setText("Doctor Department  :");

        receptionistAppointmentViewAppointmentDateLabel.setText("Appointment Date    :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(receptionistAppointmentViewPatientSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(receptionistAppointmentViewPatientNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(receptionistAppointmentViewPatientIdLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(receptionistAppointmentViewAppointmentDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(receptionistAppointmentViewPatientIdTextField)
                                .addComponent(receptionistAppointmentViewPatientNameTextField)
                                .addComponent(receptionistAppointmentViewPatientSurnameTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addComponent(receptionistAppointmentViewAppointmentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(receptionistAppointmentViewDoctorDepartmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receptionistAppointmentViewDoctorDepartmentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(receptionistAppointmentViewDoctorIdLabel)
                                    .addComponent(receptionistAppointmentViewDoctorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(receptionistAppointmentViewDoctorSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(receptionistAppointmentViewDoctorIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(receptionistAppointmentViewDoctorNameTextField)
                                    .addComponent(receptionistAppointmentViewDoctorSurnameTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(receptionistAppointmentViewAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receptionistAppointmentViewUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receptionistAppointmentViewDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receptionistAppointmentViewPatientIdLable)
                    .addComponent(receptionistAppointmentViewPatientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receptionistAppointmentViewDoctorIdLabel)
                    .addComponent(receptionistAppointmentViewDoctorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receptionistAppointmentViewAddButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receptionistAppointmentViewPatientNameLabel)
                    .addComponent(receptionistAppointmentViewPatientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receptionistAppointmentViewDoctorNameLabel)
                    .addComponent(receptionistAppointmentViewDoctorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receptionistAppointmentViewUpdateButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receptionistAppointmentViewPatientSurnameLabel)
                    .addComponent(receptionistAppointmentViewPatientSurnameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receptionistAppointmentViewDoctorSurnameLabel)
                    .addComponent(receptionistAppointmentViewDoctorSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receptionistAppointmentViewDeleteButton))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receptionistAppointmentViewAppointmentDateLabel)
                    .addComponent(receptionistAppointmentViewAppointmentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receptionistAppointmentViewDoctorDepartmentLabel)
                    .addComponent(receptionistAppointmentViewDoctorDepartmentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receptionistAppointmentViewAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receptionistAppointmentViewAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receptionistAppointmentViewAddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton receptionistAppointmentViewAddButton;
    private javax.swing.JLabel receptionistAppointmentViewAppointmentDateLabel;
    private javax.swing.JTextField receptionistAppointmentViewAppointmentDateTextField;
    private javax.swing.JButton receptionistAppointmentViewDeleteButton;
    private javax.swing.JLabel receptionistAppointmentViewDoctorDepartmentLabel;
    private javax.swing.JTextField receptionistAppointmentViewDoctorDepartmentTextField;
    private javax.swing.JLabel receptionistAppointmentViewDoctorIdLabel;
    private javax.swing.JTextField receptionistAppointmentViewDoctorIdTextField;
    private javax.swing.JLabel receptionistAppointmentViewDoctorNameLabel;
    private javax.swing.JTextField receptionistAppointmentViewDoctorNameTextField;
    private javax.swing.JLabel receptionistAppointmentViewDoctorSurnameLabel;
    private javax.swing.JTextField receptionistAppointmentViewDoctorSurnameTextField;
    private javax.swing.JLabel receptionistAppointmentViewPatientIdLable;
    private javax.swing.JTextField receptionistAppointmentViewPatientIdTextField;
    private javax.swing.JLabel receptionistAppointmentViewPatientNameLabel;
    private javax.swing.JTextField receptionistAppointmentViewPatientNameTextField;
    private javax.swing.JLabel receptionistAppointmentViewPatientSurnameLabel;
    private javax.swing.JTextField receptionistAppointmentViewPatientSurnameTextLabel;
    private javax.swing.JTable receptionistAppointmentViewTable;
    private javax.swing.JButton receptionistAppointmentViewUpdateButton;
    // End of variables declaration//GEN-END:variables
}
