package com.hms.view.admin;

import com.hms.model.Department;
import com.hms.service.HMSService;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class AdminDepartmentsView extends javax.swing.JInternalFrame {

    DefaultTableModel model = new DefaultTableModel();
    HMSService service = new HMSService();

    public AdminDepartmentsView() {
        initComponents();
        model = (DefaultTableModel) adminDepartmentsTable.getModel();
        showDepartments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminDepartmentsTable = new javax.swing.JTable();
        adminDepartmentNameLabel = new javax.swing.JLabel();
        adminDepartmentIdLabel = new javax.swing.JLabel();
        adminDepartmentIdTextField = new javax.swing.JTextField();
        adminDepartmentNameTextField = new javax.swing.JTextField();
        adminDepartmentSearchTextField = new javax.swing.JTextField();
        adminDepartmentAddButton = new javax.swing.JButton();
        adminDepartmentDeleteButton = new javax.swing.JButton();
        adminDepartmentUpdateButton = new javax.swing.JButton();
        adminDepartmentsClear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Departments");

        adminDepartmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminDepartmentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminDepartmentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminDepartmentsTable);

        adminDepartmentNameLabel.setText("Department Name  :");

        adminDepartmentIdLabel.setText("Department ID       :");

        adminDepartmentSearchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminDepartmentSearchTextFieldKeyReleased(evt);
            }
        });

        adminDepartmentAddButton.setText("Add");
        adminDepartmentAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDepartmentAddButtonActionPerformed(evt);
            }
        });

        adminDepartmentDeleteButton.setText("Delete");
        adminDepartmentDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDepartmentDeleteButtonActionPerformed(evt);
            }
        });

        adminDepartmentUpdateButton.setText("Update");
        adminDepartmentUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDepartmentUpdateButtonActionPerformed(evt);
            }
        });

        adminDepartmentsClear.setText("Clear");
        adminDepartmentsClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDepartmentsClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminDepartmentIdLabel)
                            .addComponent(adminDepartmentAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adminDepartmentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adminDepartmentNameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adminDepartmentUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(adminDepartmentDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminDepartmentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminDepartmentsClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(adminDepartmentSearchTextField))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(adminDepartmentSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDepartmentIdLabel)
                    .addComponent(adminDepartmentIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDepartmentNameLabel)
                    .addComponent(adminDepartmentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDepartmentAddButton)
                    .addComponent(adminDepartmentUpdateButton)
                    .addComponent(adminDepartmentDeleteButton)
                    .addComponent(adminDepartmentsClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminDepartmentSearchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminDepartmentSearchTextFieldKeyReleased
        String search = adminDepartmentSearchTextField.getText();
        dinamicSearch(search);
    }//GEN-LAST:event_adminDepartmentSearchTextFieldKeyReleased

    private void adminDepartmentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminDepartmentsTableMouseClicked
        int selectedRow = adminDepartmentsTable.getSelectedRow();

        adminDepartmentIdTextField.setText(model.getValueAt(selectedRow, 0).toString());
        adminDepartmentNameTextField.setText(model.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_adminDepartmentsTableMouseClicked

    private void adminDepartmentAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDepartmentAddButtonActionPerformed
        String id = adminDepartmentIdTextField.getText();
        String name = adminDepartmentNameTextField.getText();

        Department department = new Department(id, name);
        service.createDepartment(department);

        showDepartments();
        JOptionPane.showMessageDialog(this, "New Department has been Added!");

        adminDepartmentIdTextField.setText("");
        adminDepartmentNameTextField.setText("");
    }//GEN-LAST:event_adminDepartmentAddButtonActionPerformed

    private void adminDepartmentUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDepartmentUpdateButtonActionPerformed
        String id = adminDepartmentIdTextField.getText();
        String name = adminDepartmentNameTextField.getText();

        int selectedRow = adminDepartmentsTable.getSelectedRow();
        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Departments table is empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select the department which you want to update.");
            }
        } else {
            service.updateDepartment(new Department(id, name));
            showDepartments();
            JOptionPane.showMessageDialog(this, "New Department has been Updated!");

            adminDepartmentIdTextField.setText("");
            adminDepartmentNameTextField.setText("");
        }

    }//GEN-LAST:event_adminDepartmentUpdateButtonActionPerformed

    private void adminDepartmentDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDepartmentDeleteButtonActionPerformed
        String id = adminDepartmentIdTextField.getText();
        String name = adminDepartmentNameTextField.getText();

        int selectedRow = adminDepartmentsTable.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Departments table is empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Please select the department which you want to delete.");
            }
        } else {
            service.deleteDepartment(id);

            showDepartments();
            JOptionPane.showMessageDialog(this, "New Department has been Deleted!");

            adminDepartmentIdTextField.setText("");
            adminDepartmentNameTextField.setText("");
        }
    }//GEN-LAST:event_adminDepartmentDeleteButtonActionPerformed

    private void adminDepartmentsClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDepartmentsClearActionPerformed
        adminDepartmentIdTextField.setText("");
        adminDepartmentNameTextField.setText("");
    }//GEN-LAST:event_adminDepartmentsClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminDepartmentAddButton;
    private javax.swing.JButton adminDepartmentDeleteButton;
    private javax.swing.JLabel adminDepartmentIdLabel;
    private javax.swing.JTextField adminDepartmentIdTextField;
    private javax.swing.JLabel adminDepartmentNameLabel;
    private javax.swing.JTextField adminDepartmentNameTextField;
    private javax.swing.JTextField adminDepartmentSearchTextField;
    private javax.swing.JButton adminDepartmentUpdateButton;
    private javax.swing.JButton adminDepartmentsClear;
    private javax.swing.JTable adminDepartmentsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void showDepartments() {
        model.setRowCount(0);
        List<Department> departments = new LinkedList<>();

        departments = service.showDepartments();

        if (departments != null) {
            for (Department department : departments) {
                Object[] willAdd = {
                    department.getId(), department.getName()
                };
                model.addRow(willAdd);
            }
        }
    }

    private void dinamicSearch(String search) {
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);

        adminDepartmentsTable.setRowSorter(tableRowSorter);

        tableRowSorter.setRowFilter(RowFilter.regexFilter(search));
    }
}
