
package com.hms.view.admin;

import com.hms.view.Login;

public class HMSAdminMainView extends javax.swing.JFrame {

    public HMSAdminMainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminDesktopPane = new javax.swing.JDesktopPane();
        adminMenuBar = new javax.swing.JMenuBar();
        adminFileMenu = new javax.swing.JMenu();
        adminFileMenuItemLogOut = new javax.swing.JMenuItem();
        adminFileMenuItemExit = new javax.swing.JMenuItem();
        adminOperationsMenu = new javax.swing.JMenu();
        adminOperationsMenuItemAdmins = new javax.swing.JMenuItem();
        adminOperationsMenuItemDepartments = new javax.swing.JMenuItem();
        adminOperationsMenuItemDoctors = new javax.swing.JMenuItem();
        adminOperationsMenuItemReceptionists = new javax.swing.JMenuItem();
        adminOperationsMenuItemUsers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMS Admin");

        javax.swing.GroupLayout adminDesktopPaneLayout = new javax.swing.GroupLayout(adminDesktopPane);
        adminDesktopPane.setLayout(adminDesktopPaneLayout);
        adminDesktopPaneLayout.setHorizontalGroup(
            adminDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        adminDesktopPaneLayout.setVerticalGroup(
            adminDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        adminFileMenu.setText("File");

        adminFileMenuItemLogOut.setText("Log Out");
        adminFileMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminFileMenuItemLogOutActionPerformed(evt);
            }
        });
        adminFileMenu.add(adminFileMenuItemLogOut);

        adminFileMenuItemExit.setText("Exit");
        adminFileMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminFileMenuItemExitActionPerformed(evt);
            }
        });
        adminFileMenu.add(adminFileMenuItemExit);

        adminMenuBar.add(adminFileMenu);

        adminOperationsMenu.setText("Operations");

        adminOperationsMenuItemAdmins.setText("Admins");
        adminOperationsMenuItemAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminOperationsMenuItemAdminsActionPerformed(evt);
            }
        });
        adminOperationsMenu.add(adminOperationsMenuItemAdmins);

        adminOperationsMenuItemDepartments.setText("Departments");
        adminOperationsMenuItemDepartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminOperationsMenuItemDepartmentsActionPerformed(evt);
            }
        });
        adminOperationsMenu.add(adminOperationsMenuItemDepartments);

        adminOperationsMenuItemDoctors.setText("Doctors");
        adminOperationsMenuItemDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminOperationsMenuItemDoctorsActionPerformed(evt);
            }
        });
        adminOperationsMenu.add(adminOperationsMenuItemDoctors);

        adminOperationsMenuItemReceptionists.setText("Receptionists");
        adminOperationsMenuItemReceptionists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminOperationsMenuItemReceptionistsActionPerformed(evt);
            }
        });
        adminOperationsMenu.add(adminOperationsMenuItemReceptionists);

        adminOperationsMenuItemUsers.setText("Users");
        adminOperationsMenuItemUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminOperationsMenuItemUsersActionPerformed(evt);
            }
        });
        adminOperationsMenu.add(adminOperationsMenuItemUsers);

        adminMenuBar.add(adminOperationsMenu);

        setJMenuBar(adminMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminFileMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminFileMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_adminFileMenuItemExitActionPerformed

    private void adminOperationsMenuItemAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminOperationsMenuItemAdminsActionPerformed
        AdminAdminsView adminAdminsView = new AdminAdminsView();
        adminDesktopPane.add(adminAdminsView).setVisible(true);
    }//GEN-LAST:event_adminOperationsMenuItemAdminsActionPerformed

    private void adminFileMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminFileMenuItemLogOutActionPerformed
        Login login = new Login();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_adminFileMenuItemLogOutActionPerformed

    private void adminOperationsMenuItemDepartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminOperationsMenuItemDepartmentsActionPerformed
        AdminDepartmentsView adminDepartmentsView = new AdminDepartmentsView();
        adminDesktopPane.add(adminDepartmentsView).setVisible(true);
    }//GEN-LAST:event_adminOperationsMenuItemDepartmentsActionPerformed

    private void adminOperationsMenuItemDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminOperationsMenuItemDoctorsActionPerformed
        AdminDoctorsView adminDoctorsView = new AdminDoctorsView();
        adminDesktopPane.add(adminDoctorsView).setVisible(true);
    }//GEN-LAST:event_adminOperationsMenuItemDoctorsActionPerformed

    private void adminOperationsMenuItemReceptionistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminOperationsMenuItemReceptionistsActionPerformed
        AdminReceptionistsView adminReceptionistsView = new AdminReceptionistsView();
        adminDesktopPane.add(adminReceptionistsView).setVisible(true);
    }//GEN-LAST:event_adminOperationsMenuItemReceptionistsActionPerformed

    private void adminOperationsMenuItemUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminOperationsMenuItemUsersActionPerformed
        AdminUsersView adminUsersView = new AdminUsersView();
        adminDesktopPane.add(adminUsersView).setVisible(true);
    }//GEN-LAST:event_adminOperationsMenuItemUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane adminDesktopPane;
    private javax.swing.JMenu adminFileMenu;
    private javax.swing.JMenuItem adminFileMenuItemExit;
    private javax.swing.JMenuItem adminFileMenuItemLogOut;
    private javax.swing.JMenuBar adminMenuBar;
    private javax.swing.JMenu adminOperationsMenu;
    private javax.swing.JMenuItem adminOperationsMenuItemAdmins;
    private javax.swing.JMenuItem adminOperationsMenuItemDepartments;
    private javax.swing.JMenuItem adminOperationsMenuItemDoctors;
    private javax.swing.JMenuItem adminOperationsMenuItemReceptionists;
    private javax.swing.JMenuItem adminOperationsMenuItemUsers;
    // End of variables declaration//GEN-END:variables
}
