package com.hms.view.doctor;

import com.hms.model.Prescription;
import com.hms.service.HMSService;
import java.awt.print.PrinterException;
import java.sql.Date;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

public class DoctorPrescriptionView extends javax.swing.JInternalFrame {

    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    HMSService service = new HMSService();

    public DoctorPrescriptionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorPrescriptionViewMedicineNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewMedicineNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDailyDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewNumberOfTabletsLabel = new javax.swing.JLabel();
        doctorPrescriptionViewDailyDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewNumberOfTabletsTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsSurnameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsSurnameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsGenderLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsGenderComboBox = new javax.swing.JComboBox<>();
        doctorPrescriptionViewPatientsBirthdateLabel = new javax.swing.JLabel();
        doctorPrescriptionViewExplanationLabel = new javax.swing.JLabel();
        doctorPrescriptionViewExplanationTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionPane = new javax.swing.JPanel();
        doctorPrescriptionViewPrescriptionTextField = new javax.swing.JTextField();
        doctorPrescriptionViewSaveButton = new javax.swing.JButton();
        doctorPrescriptionViewPrintButton = new javax.swing.JButton();
        doctorPrescriptionViewAnamnesisLabel = new javax.swing.JLabel();
        doctorPrescriptionViewAnamnesisTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionButton = new javax.swing.JButton();
        doctorPrescriptionViewUpdateButton = new javax.swing.JButton();
        doctorPrescriptionViewPrescriptionIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionSearchTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionSearchLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsBirthdateDateChooser = new com.toedter.calendar.JDateChooser();
        doctorPrescriptionViewMessageLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Prescription");

        doctorPrescriptionViewMedicineNameLabel.setText("Name of Medicine   :");

        doctorPrescriptionViewDoseLabel.setText("Dose (mg)              :");

        doctorPrescriptionViewNumberOfTabletsLabel.setText("Number of Tablets :");

        doctorPrescriptionViewDailyDoseLabel.setText("Daily Dose              :");

        doctorPrescriptionViewPatientIdLabel.setText("Patient ID               :");

        doctorPrescriptionViewPatientsIdTextField.setEditable(false);

        doctorPrescriptionViewPatientsNameLabel.setText("Name                      :");

        doctorPrescriptionViewPatientsNameTextField.setEditable(false);

        doctorPrescriptionViewPatientsSurnameTextField.setEditable(false);

        doctorPrescriptionViewPatientsSurnameLabel.setText("Surname                 :");

        doctorPrescriptionViewPatientsGenderLabel.setText("Gender                   :");

        doctorPrescriptionViewPatientsGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        doctorPrescriptionViewPatientsBirthdateLabel.setText("Birthdate                :");

        doctorPrescriptionViewExplanationLabel.setText("Explanation            :");

        doctorPrescriptionViewPrescriptionPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        doctorPrescriptionViewPrescriptionTextField.setEditable(false);

        javax.swing.GroupLayout doctorPrescriptionViewPrescriptionPaneLayout = new javax.swing.GroupLayout(doctorPrescriptionViewPrescriptionPane);
        doctorPrescriptionViewPrescriptionPane.setLayout(doctorPrescriptionViewPrescriptionPaneLayout);
        doctorPrescriptionViewPrescriptionPaneLayout.setHorizontalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorPrescriptionViewPrescriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        doctorPrescriptionViewPrescriptionPaneLayout.setVerticalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorPrescriptionViewPrescriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        doctorPrescriptionViewSaveButton.setText("Save");
        doctorPrescriptionViewSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewSaveButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrintButton.setText("Print");
        doctorPrescriptionViewPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrintButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewAnamnesisLabel.setText("Anamnesis             :");

        doctorPrescriptionViewPrescriptionButton.setText("Prescription");
        doctorPrescriptionViewPrescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrescriptionButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewUpdateButton.setText("Update");
        doctorPrescriptionViewUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewUpdateButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrescriptionIdLabel.setText("Prescription ID       :");

        doctorPrescriptionViewPrescriptionSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrescriptionSearchLabel.setText("Search Previous Prescription By Prescription ID:");

        doctorPrescriptionViewPatientsBirthdateDateChooser.setDateFormatString("yyyy MM dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(doctorPrescriptionViewPrescriptionSearchTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doctorPrescriptionViewPatientsSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPatientsSurnameTextField)
                            .addComponent(doctorPrescriptionViewPatientsNameTextField)
                            .addComponent(doctorPrescriptionViewPatientsIdTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsGenderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewAnamnesisLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPatientsGenderComboBox, 0, 186, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(doctorPrescriptionViewPrescriptionSearchLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorPrescriptionViewAnamnesisTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewSaveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPrescriptionButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctorPrescriptionViewUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(doctorPrescriptionViewMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDailyDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewMedicineNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewMedicineNameTextField)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(doctorPrescriptionViewPrescriptionIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(doctorPrescriptionViewPrescriptionIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addComponent(doctorPrescriptionViewExplanationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doctorPrescriptionViewExplanationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewMedicineNameLabel)
                            .addComponent(doctorPrescriptionViewMedicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewDoseLabel)
                            .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsLabel)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewDailyDoseLabel)
                            .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPrescriptionIdLabel)
                            .addComponent(doctorPrescriptionViewPrescriptionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewExplanationLabel)
                            .addComponent(doctorPrescriptionViewMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientIdLabel)
                            .addComponent(doctorPrescriptionViewPatientsIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsNameLabel)
                            .addComponent(doctorPrescriptionViewPatientsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsSurnameLabel)
                            .addComponent(doctorPrescriptionViewPatientsSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateLabel)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsGenderLabel)
                            .addComponent(doctorPrescriptionViewPatientsGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorPrescriptionViewExplanationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(doctorPrescriptionViewAnamnesisLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewAnamnesisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorPrescriptionViewPrescriptionSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorPrescriptionViewPrescriptionSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewUpdateButton)
                            .addComponent(doctorPrescriptionViewSaveButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPrescriptionButton)
                            .addComponent(doctorPrescriptionViewPrintButton)))
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorPrescriptionViewUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewUpdateButtonActionPerformed
        doctorPrescriptionViewMessageLabel.setText("");
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = (Date) doctorPrescriptionViewPatientsBirthdateDateChooser.getDate();
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        int doseMg = Integer.parseInt(doctorPrescriptionViewDoseTextField.getText());
        int numberOfTablets = Integer.parseInt(doctorPrescriptionViewNumberOfTabletsTextField.getText());
        int dailyDose = Integer.parseInt(doctorPrescriptionViewDailyDoseTextField.getText());
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();

//        service.updatePrescription(new Prescription(prescriptionId, patientId, doctorId, nameOfMedicine, doseMg, numberOfTablets, dailyDose, explanation));

        doctorPrescriptionViewMessageLabel.setText("Prescription is updated!");
    }//GEN-LAST:event_doctorPrescriptionViewUpdateButtonActionPerformed

    private void doctorPrescriptionViewPrescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrescriptionButtonActionPerformed
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = (Date) doctorPrescriptionViewPatientsBirthdateDateChooser.getDate();
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        String doseMg = doctorPrescriptionViewDoseTextField.getText();
        String numberOfTablets = doctorPrescriptionViewNumberOfTabletsTextField.getText();
        String dailyDose = doctorPrescriptionViewDailyDoseTextField.getText();
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();

        doctorPrescriptionViewPrescriptionTextField.setText("\t\n\tHospital Management System\n"
                + "Patient ID:\t\t" + patientId
                + "Patient Name:\t\t" + patientName + " " + patientSurname
                + "Gender:\t\t" + patientGender
                + "Date of Birth:\t\t" + patientBirthdate
                + "\nPrescription ID:\t\t" + prescriptionId
                + "Medicine Name:\t\t" + nameOfMedicine
                + "Dose (mg):\t\t" + doseMg
                + "Number of Tablets:\t\t" + numberOfTablets
                + "Daily Dose:\t\t" + dailyDose
                + "Explanation:\t\t" + explanation);


    }//GEN-LAST:event_doctorPrescriptionViewPrescriptionButtonActionPerformed

    private void doctorPrescriptionViewSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewSaveButtonActionPerformed
        // TODO add your handling code here:
        doctorPrescriptionViewMessageLabel.setText("");
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = (Date) doctorPrescriptionViewPatientsBirthdateDateChooser.getDate();
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        int doseMg = Integer.parseInt(doctorPrescriptionViewDoseTextField.getText());
        int numberOfTablets = Integer.parseInt(doctorPrescriptionViewNumberOfTabletsTextField.getText());
        int dailyDose = Integer.parseInt(doctorPrescriptionViewDailyDoseTextField.getText());
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();

//        service.createPrescription(new Prescription(prescriptionId, patientId, doctorId, nameOfMedicine, doseMg, numberOfTablets, dailyDose, explanation));

        doctorPrescriptionViewMessageLabel.setText("Prescription is saved!");
    }//GEN-LAST:event_doctorPrescriptionViewSaveButtonActionPerformed

    private void doctorPrescriptionViewPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrintButtonActionPerformed
        try {
            doctorPrescriptionViewPrescriptionTextField.print();
        } catch (PrinterException ex) {
            Logger.getLogger(DoctorPrescriptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doctorPrescriptionViewPrintButtonActionPerformed

    private void doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed
        // TODO add your handling code here:
        String prescriptionId = doctorPrescriptionViewPrescriptionSearchTextField.getText();

        List<Prescription> prescription = new LinkedList<>();
        prescription = service.prescription(prescriptionId);

        doctorPrescriptionViewPrescriptionIdTextField.setText(prescription.get(0).toString());
        doctorPrescriptionViewPatientsIdTextField.setText(prescription.get(1).toString());
//        doctorPrescriptionViewPatientsNameTextField.setText();
//        doctorPrescriptionViewPatientsSurnameTextField.setText();
//        doctorPrescriptionViewPatientsBirthdateDateChooser.setDate();
//        doctorPrescriptionViewPatientsGenderComboBox.setSelectedItem();
        doctorPrescriptionViewMedicineNameTextField.setText(prescription.get(3).toString());
        doctorPrescriptionViewDoseTextField.setText(prescription.get(4).toString());
        doctorPrescriptionViewNumberOfTabletsTextField.setText(prescription.get(5).toString());
        doctorPrescriptionViewDailyDoseTextField.setText(prescription.get(6).toString());
        doctorPrescriptionViewExplanationTextField.setText(prescription.get(7).toString());

    }//GEN-LAST:event_doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doctorPrescriptionViewAnamnesisLabel;
    private javax.swing.JTextField doctorPrescriptionViewAnamnesisTextField;
    private javax.swing.JLabel doctorPrescriptionViewDailyDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDailyDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewExplanationLabel;
    private javax.swing.JTextField doctorPrescriptionViewExplanationTextField;
    private javax.swing.JLabel doctorPrescriptionViewMedicineNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewMedicineNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewMessageLabel;
    private javax.swing.JLabel doctorPrescriptionViewNumberOfTabletsLabel;
    private javax.swing.JTextField doctorPrescriptionViewNumberOfTabletsTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientIdLabel;
    private com.toedter.calendar.JDateChooser doctorPrescriptionViewPatientsBirthdateDateChooser;
    private javax.swing.JLabel doctorPrescriptionViewPatientsBirthdateLabel;
    private javax.swing.JComboBox<String> doctorPrescriptionViewPatientsGenderComboBox;
    private javax.swing.JLabel doctorPrescriptionViewPatientsGenderLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsIdTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsSurnameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsSurnameTextField;
    private javax.swing.JButton doctorPrescriptionViewPrescriptionButton;
    private javax.swing.JLabel doctorPrescriptionViewPrescriptionIdLabel;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionIdTextField;
    private javax.swing.JPanel doctorPrescriptionViewPrescriptionPane;
    private javax.swing.JLabel doctorPrescriptionViewPrescriptionSearchLabel;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionSearchTextField;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionTextField;
    private javax.swing.JButton doctorPrescriptionViewPrintButton;
    private javax.swing.JButton doctorPrescriptionViewSaveButton;
    private javax.swing.JButton doctorPrescriptionViewUpdateButton;
    // End of variables declaration//GEN-END:variables

}
