package com.hms.view.doctor;

import com.hms.model.Prescription;
import com.hms.service.HMSService;
import java.awt.print.PrinterException;
import java.sql.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

public class DoctorsPrescriptionView extends javax.swing.JDialog {

    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    HMSService service = new HMSService();

    public DoctorsPrescriptionView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    DoctorsPrescriptionView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorPrescriptionViewSaveButton = new javax.swing.JButton();
        doctorPrescriptionViewAnamnesisTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewAnamnesisLabel = new javax.swing.JLabel();
        doctorPrescriptionViewDailyDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewMedicineNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewMedicineNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewUpdateButton = new javax.swing.JButton();
        doctorPrescriptionViewPatientsGenderLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsBirthdateLabel = new javax.swing.JLabel();
        doctorPrescriptionViewDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsSurnameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewNumberOfTabletsTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionButton = new javax.swing.JButton();
        doctorPrescriptionViewExplanationLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionSearchTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsGenderComboBox = new javax.swing.JComboBox<>();
        doctorPrescriptionViewNumberOfTabletsLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionSearchLabel = new javax.swing.JLabel();
        doctorPrescriptionViewExplanationTextField = new javax.swing.JTextField();
        doctorPrescriptionViewMessageLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsSurnameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsBirthdateDateChooser = new com.toedter.calendar.JDateChooser();
        doctorPrescriptionViewPatientsNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDailyDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrintButton = new javax.swing.JButton();
        doctorPrescriptionViewPrescriptionPane = new javax.swing.JPanel();
        doctorPrescriptionViewPrescriptionTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prescription");
        setPreferredSize(new java.awt.Dimension(780, 750));

        doctorPrescriptionViewSaveButton.setText("Save");
        doctorPrescriptionViewSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewSaveButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPatientIdLabel.setText("Patient ID               :");

        doctorPrescriptionViewAnamnesisLabel.setText("Anamnesis             :");

        doctorPrescriptionViewMedicineNameLabel.setText("Name of Medicine   :");

        doctorPrescriptionViewUpdateButton.setText("Update");
        doctorPrescriptionViewUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewUpdateButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPatientsGenderLabel.setText("Gender                   :");

        doctorPrescriptionViewPatientsBirthdateLabel.setText("Birthdate                :");

        doctorPrescriptionViewPatientsSurnameTextField.setEditable(false);

        doctorPrescriptionViewPrescriptionButton.setText("Prescription");
        doctorPrescriptionViewPrescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrescriptionButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewExplanationLabel.setText("Explanation            :");

        doctorPrescriptionViewPrescriptionIdLabel.setText("Prescription ID       :");

        doctorPrescriptionViewPatientsNameLabel.setText("Name                      :");

        doctorPrescriptionViewPrescriptionSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPatientsGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        doctorPrescriptionViewNumberOfTabletsLabel.setText("Number of Tablets :");

        doctorPrescriptionViewPrescriptionSearchLabel.setText("Search Previous Prescription By Prescription ID:");

        doctorPrescriptionViewPatientsSurnameLabel.setText("Surname                 :");

        doctorPrescriptionViewPatientsBirthdateDateChooser.setDateFormatString("yyyy-MM-dd");

        doctorPrescriptionViewPatientsNameTextField.setEditable(false);

        doctorPrescriptionViewPatientsIdTextField.setEditable(false);

        doctorPrescriptionViewDailyDoseLabel.setText("Daily Dose              :");

        doctorPrescriptionViewDoseLabel.setText("Dose (mg)              :");

        doctorPrescriptionViewPrintButton.setText("Print");
        doctorPrescriptionViewPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrintButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrescriptionPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        doctorPrescriptionViewPrescriptionTextField.setEditable(false);

        javax.swing.GroupLayout doctorPrescriptionViewPrescriptionPaneLayout = new javax.swing.GroupLayout(doctorPrescriptionViewPrescriptionPane);
        doctorPrescriptionViewPrescriptionPane.setLayout(doctorPrescriptionViewPrescriptionPaneLayout);
        doctorPrescriptionViewPrescriptionPaneLayout.setHorizontalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorPrescriptionViewPrescriptionTextField)
        );
        doctorPrescriptionViewPrescriptionPaneLayout.setVerticalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorPrescriptionViewPrescriptionTextField)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(doctorPrescriptionViewPrescriptionSearchTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doctorPrescriptionViewPatientsSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPatientsSurnameTextField)
                            .addComponent(doctorPrescriptionViewPatientsNameTextField)
                            .addComponent(doctorPrescriptionViewPatientsIdTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewPatientsGenderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewAnamnesisLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPatientsGenderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(doctorPrescriptionViewPrescriptionSearchLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorPrescriptionViewAnamnesisTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewSaveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPrescriptionButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctorPrescriptionViewUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(doctorPrescriptionViewMessageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDailyDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewMedicineNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewMedicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewPrescriptionIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorPrescriptionViewPrescriptionIdTextField))
                    .addComponent(doctorPrescriptionViewExplanationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorPrescriptionViewExplanationTextField)
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewMedicineNameLabel)
                            .addComponent(doctorPrescriptionViewMedicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewDoseLabel)
                            .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsLabel)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewDailyDoseLabel)
                            .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPrescriptionIdLabel)
                            .addComponent(doctorPrescriptionViewPrescriptionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(doctorPrescriptionViewExplanationLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientIdLabel)
                            .addComponent(doctorPrescriptionViewPatientsIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsNameLabel)
                            .addComponent(doctorPrescriptionViewPatientsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsSurnameLabel)
                            .addComponent(doctorPrescriptionViewPatientsSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateLabel)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsGenderLabel)
                            .addComponent(doctorPrescriptionViewPatientsGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(doctorPrescriptionViewAnamnesisLabel))
                    .addComponent(doctorPrescriptionViewExplanationTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewAnamnesisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorPrescriptionViewPrescriptionSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorPrescriptionViewPrescriptionSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewUpdateButton)
                            .addComponent(doctorPrescriptionViewSaveButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPrescriptionButton)
                            .addComponent(doctorPrescriptionViewPrintButton)))
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorPrescriptionViewSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewSaveButtonActionPerformed
        // TODO add your handling code here:
        doctorPrescriptionViewMessageLabel.setText("");
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = (Date) doctorPrescriptionViewPatientsBirthdateDateChooser.getDate();
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        int doseMg = Integer.parseInt(doctorPrescriptionViewDoseTextField.getText());
        int numberOfTablets = Integer.parseInt(doctorPrescriptionViewNumberOfTabletsTextField.getText());
        int dailyDose = Integer.parseInt(doctorPrescriptionViewDailyDoseTextField.getText());
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();

        //        service.createPrescription(new Prescription(prescriptionId, patientId, doctorId, nameOfMedicine, doseMg, numberOfTablets, dailyDose, explanation));
        doctorPrescriptionViewMessageLabel.setText("Prescription is saved!");
    }//GEN-LAST:event_doctorPrescriptionViewSaveButtonActionPerformed

    private void doctorPrescriptionViewUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewUpdateButtonActionPerformed
        doctorPrescriptionViewMessageLabel.setText("");
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = (Date) doctorPrescriptionViewPatientsBirthdateDateChooser.getDate();
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        int doseMg = Integer.parseInt(doctorPrescriptionViewDoseTextField.getText());
        int numberOfTablets = Integer.parseInt(doctorPrescriptionViewNumberOfTabletsTextField.getText());
        int dailyDose = Integer.parseInt(doctorPrescriptionViewDailyDoseTextField.getText());
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();

        //        service.updatePrescription(new Prescription(prescriptionId, patientId, doctorId, nameOfMedicine, doseMg, numberOfTablets, dailyDose, explanation));
        doctorPrescriptionViewMessageLabel.setText("Prescription is updated!");
    }//GEN-LAST:event_doctorPrescriptionViewUpdateButtonActionPerformed

    private void doctorPrescriptionViewPrescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrescriptionButtonActionPerformed
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = (Date) doctorPrescriptionViewPatientsBirthdateDateChooser.getDate();
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        String doseMg = doctorPrescriptionViewDoseTextField.getText();
        String numberOfTablets = doctorPrescriptionViewNumberOfTabletsTextField.getText();
        String dailyDose = doctorPrescriptionViewDailyDoseTextField.getText();
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();

        doctorPrescriptionViewPrescriptionTextField.setText("\t\n\tHospital Management System\n"
                + "Patient ID:\t\t" + patientId
                + "Patient Name:\t\t" + patientName + " " + patientSurname
                + "Gender:\t\t" + patientGender
                + "Date of Birth:\t\t" + patientBirthdate
                + "\nPrescription ID:\t\t" + prescriptionId
                + "Medicine Name:\t\t" + nameOfMedicine
                + "Dose (mg):\t\t" + doseMg
                + "Number of Tablets:\t\t" + numberOfTablets
                + "Daily Dose:\t\t" + dailyDose
                + "Explanation:\t\t" + explanation);

    }//GEN-LAST:event_doctorPrescriptionViewPrescriptionButtonActionPerformed

    private void doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed
        String prescriptionId = doctorPrescriptionViewPrescriptionSearchTextField.getText();

        List<Prescription> prescription = new LinkedList<>();
        prescription = service.prescription(prescriptionId);

        doctorPrescriptionViewPrescriptionIdTextField.setText(prescription.get(0).toString());
        doctorPrescriptionViewPatientsIdTextField.setText(prescription.get(1).toString());
        //        doctorPrescriptionViewPatientsNameTextField.setText();
        //        doctorPrescriptionViewPatientsSurnameTextField.setText();
        //        doctorPrescriptionViewPatientsBirthdateDateChooser.setDate();
        //        doctorPrescriptionViewPatientsGenderComboBox.setSelectedItem();
        doctorPrescriptionViewMedicineNameTextField.setText(prescription.get(3).toString());
        doctorPrescriptionViewDoseTextField.setText(prescription.get(4).toString());
        doctorPrescriptionViewNumberOfTabletsTextField.setText(prescription.get(5).toString());
        doctorPrescriptionViewDailyDoseTextField.setText(prescription.get(6).toString());
        doctorPrescriptionViewExplanationTextField.setText(prescription.get(7).toString());
    }//GEN-LAST:event_doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed

    private void doctorPrescriptionViewPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrintButtonActionPerformed
        try {
            doctorPrescriptionViewPrescriptionTextField.print();
        } catch (PrinterException ex) {
            Logger.getLogger(DoctorPrescriptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doctorPrescriptionViewPrintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorsPrescriptionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorsPrescriptionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorsPrescriptionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorsPrescriptionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DoctorsPrescriptionView dialog = new DoctorsPrescriptionView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doctorPrescriptionViewAnamnesisLabel;
    private javax.swing.JTextField doctorPrescriptionViewAnamnesisTextField;
    private javax.swing.JLabel doctorPrescriptionViewDailyDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDailyDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewExplanationLabel;
    private javax.swing.JTextField doctorPrescriptionViewExplanationTextField;
    private javax.swing.JLabel doctorPrescriptionViewMedicineNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewMedicineNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewMessageLabel;
    private javax.swing.JLabel doctorPrescriptionViewNumberOfTabletsLabel;
    private javax.swing.JTextField doctorPrescriptionViewNumberOfTabletsTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientIdLabel;
    private com.toedter.calendar.JDateChooser doctorPrescriptionViewPatientsBirthdateDateChooser;
    private javax.swing.JLabel doctorPrescriptionViewPatientsBirthdateLabel;
    private javax.swing.JComboBox<String> doctorPrescriptionViewPatientsGenderComboBox;
    private javax.swing.JLabel doctorPrescriptionViewPatientsGenderLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsIdTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsSurnameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsSurnameTextField;
    private javax.swing.JButton doctorPrescriptionViewPrescriptionButton;
    private javax.swing.JLabel doctorPrescriptionViewPrescriptionIdLabel;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionIdTextField;
    private javax.swing.JPanel doctorPrescriptionViewPrescriptionPane;
    private javax.swing.JLabel doctorPrescriptionViewPrescriptionSearchLabel;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionSearchTextField;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionTextField;
    private javax.swing.JButton doctorPrescriptionViewPrintButton;
    private javax.swing.JButton doctorPrescriptionViewSaveButton;
    private javax.swing.JButton doctorPrescriptionViewUpdateButton;
    // End of variables declaration//GEN-END:variables
}
