package com.hms.view.doctor;

import com.hms.model.Prescription;
import com.hms.service.HMSService;
import java.awt.print.PrinterException;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

public class DoctorsPrescriptionView extends javax.swing.JDialog {

    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    List<String> patientInfo = new LinkedList();
    List<String> prescription = new LinkedList();
    HMSService service = new HMSService();

    public DoctorsPrescriptionView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    DoctorsPrescriptionView() {
        initComponents();

    }

    DoctorsPrescriptionView(List<String> patientInfo) {
        initComponents();
        this.patientInfo = patientInfo;
        doctorPrescriptionViewPatientsIdTextField.setText(patientInfo.get(0));
        doctorPrescriptionViewPatientsNameTextField.setText(patientInfo.get(1));
        doctorPrescriptionViewPatientsSurnameTextField.setText(patientInfo.get(2));
        doctorPrescriptionViewPatientsGenderComboBox.setSelectedItem(patientInfo.get(3));
        try {
            doctorPrescriptionViewPatientsBirthdateDateChooser.setDate(simpleDateFormat.parse(patientInfo.get(4)));
        } catch (ParseException ex) {
            Logger.getLogger(DoctorsPrescriptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
        doctorPrescriptionViewAnamnesisTextField.setText(patientInfo.get(7));

        if (patientInfo.get(8) != "No prescription") {
            prescription = service.prescription(patientInfo.get(8));
            
            doctorPrescriptionViewPrescriptionIdTextField.setText(patientInfo.get(8));
            doctorPrescriptionViewMedicineNameTextField.setText(prescription.get(2));
            doctorPrescriptionViewDoseTextField.setText(prescription.get(3));
            doctorPrescriptionViewNumberOfTabletsTextField.setText(prescription.get(4));
            doctorPrescriptionViewDailyDoseTextField.setText(prescription.get(5));
            doctorPrescriptionViewExplanationTextField.setText(prescription.get(6));

        } else {
            doctorPrescriptionViewPrescriptionIdTextField.setText(lastId());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorPrescriptionViewSaveButton = new javax.swing.JButton();
        doctorPrescriptionViewAnamnesisTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewAnamnesisLabel = new javax.swing.JLabel();
        doctorPrescriptionViewDailyDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewMedicineNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewMedicineNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewUpdateButton = new javax.swing.JButton();
        doctorPrescriptionViewPatientsGenderLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsBirthdateLabel = new javax.swing.JLabel();
        doctorPrescriptionViewDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsSurnameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewNumberOfTabletsTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionButton = new javax.swing.JButton();
        doctorPrescriptionViewExplanationLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsGenderComboBox = new javax.swing.JComboBox<>();
        doctorPrescriptionViewNumberOfTabletsLabel = new javax.swing.JLabel();
        doctorPrescriptionViewExplanationTextField = new javax.swing.JTextField();
        doctorPrescriptionViewMessageLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsSurnameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsBirthdateDateChooser = new com.toedter.calendar.JDateChooser();
        doctorPrescriptionViewPatientsNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDailyDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrintButton = new javax.swing.JButton();
        doctorPrescriptionViewPrescriptionPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorsPrescriptionViewPrescriptionTextArea = new javax.swing.JTextArea();
        doctorPrescriptionViewDoctorIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewDoctorIdTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prescription");
        setPreferredSize(new java.awt.Dimension(780, 750));

        doctorPrescriptionViewSaveButton.setText("Save");
        doctorPrescriptionViewSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewSaveButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewAnamnesisTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        doctorPrescriptionViewPatientIdLabel.setText("Patient ID               :");

        doctorPrescriptionViewAnamnesisLabel.setText("Anamnesis             :");

        doctorPrescriptionViewMedicineNameLabel.setText("Name of Medicine   :");

        doctorPrescriptionViewUpdateButton.setText("Update");
        doctorPrescriptionViewUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewUpdateButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPatientsGenderLabel.setText("Gender                   :");

        doctorPrescriptionViewPatientsBirthdateLabel.setText("Birthdate                :");

        doctorPrescriptionViewPatientsSurnameTextField.setEditable(false);

        doctorPrescriptionViewPrescriptionButton.setText("Prescription");
        doctorPrescriptionViewPrescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrescriptionButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewExplanationLabel.setText("Explanation            :");

        doctorPrescriptionViewPrescriptionIdLabel.setText("Prescription ID       :");

        doctorPrescriptionViewPatientsNameLabel.setText("Name                      :");

        doctorPrescriptionViewPatientsGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        doctorPrescriptionViewNumberOfTabletsLabel.setText("Number of Tablets :");

        doctorPrescriptionViewPatientsSurnameLabel.setText("Surname                 :");

        doctorPrescriptionViewPatientsBirthdateDateChooser.setDateFormatString("yyyy-MM-dd");

        doctorPrescriptionViewPatientsNameTextField.setEditable(false);

        doctorPrescriptionViewPatientsIdTextField.setEditable(false);

        doctorPrescriptionViewDailyDoseLabel.setText("Daily Dose              :");

        doctorPrescriptionViewDoseLabel.setText("Dose (mg)              :");

        doctorPrescriptionViewPrintButton.setText("Print");
        doctorPrescriptionViewPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrintButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrescriptionPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        doctorsPrescriptionViewPrescriptionTextArea.setColumns(20);
        doctorsPrescriptionViewPrescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(doctorsPrescriptionViewPrescriptionTextArea);

        javax.swing.GroupLayout doctorPrescriptionViewPrescriptionPaneLayout = new javax.swing.GroupLayout(doctorPrescriptionViewPrescriptionPane);
        doctorPrescriptionViewPrescriptionPane.setLayout(doctorPrescriptionViewPrescriptionPaneLayout);
        doctorPrescriptionViewPrescriptionPaneLayout.setHorizontalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        doctorPrescriptionViewPrescriptionPaneLayout.setVerticalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        doctorPrescriptionViewDoctorIdLabel.setText("Doctor ID                :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doctorPrescriptionViewPatientsSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientIdLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPatientsSurnameTextField)
                            .addComponent(doctorPrescriptionViewPatientsIdTextField)
                            .addComponent(doctorPrescriptionViewPatientsNameTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewPatientsGenderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewAnamnesisLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPatientsGenderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(doctorPrescriptionViewAnamnesisTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewSaveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewPrescriptionButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctorPrescriptionViewUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(doctorPrescriptionViewMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewDoctorIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorPrescriptionViewDoctorIdTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDailyDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewMedicineNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewMedicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(doctorPrescriptionViewExplanationTextField)
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doctorPrescriptionViewPrescriptionIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewExplanationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorPrescriptionViewPrescriptionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewDoctorIdLabel)
                        .addComponent(doctorPrescriptionViewDoctorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewMedicineNameLabel)
                        .addComponent(doctorPrescriptionViewMedicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewPatientIdLabel)
                        .addComponent(doctorPrescriptionViewPatientsIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewDoseLabel)
                        .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewPatientsNameLabel)
                        .addComponent(doctorPrescriptionViewPatientsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewNumberOfTabletsLabel)
                        .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewPatientsSurnameLabel)
                        .addComponent(doctorPrescriptionViewPatientsSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewDailyDoseLabel)
                        .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctorPrescriptionViewPrescriptionIdLabel)
                        .addComponent(doctorPrescriptionViewPrescriptionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doctorPrescriptionViewPatientsBirthdateLabel)
                    .addComponent(doctorPrescriptionViewPatientsBirthdateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorPrescriptionViewExplanationLabel)
                    .addComponent(doctorPrescriptionViewPatientsGenderLabel)
                    .addComponent(doctorPrescriptionViewPatientsGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(doctorPrescriptionViewAnamnesisLabel))
                    .addComponent(doctorPrescriptionViewExplanationTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewAnamnesisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewUpdateButton)
                            .addComponent(doctorPrescriptionViewSaveButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPrescriptionButton)
                            .addComponent(doctorPrescriptionViewPrintButton)))
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorPrescriptionViewSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewSaveButtonActionPerformed
        // TODO add your handling code here:
        doctorPrescriptionViewMessageLabel.setText("");
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = new java.sql.Date(doctorPrescriptionViewPatientsBirthdateDateChooser.getDate().getTime());
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        int doseMg = Integer.parseInt(doctorPrescriptionViewDoseTextField.getText());
        int numberOfTablets = Integer.parseInt(doctorPrescriptionViewNumberOfTabletsTextField.getText());
        int dailyDose = Integer.parseInt(doctorPrescriptionViewDailyDoseTextField.getText());
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();
        String doctorId = doctorPrescriptionViewDoctorIdTextField.getText();
        String anamnesis = doctorPrescriptionViewAnamnesisTextField.getText();

        service.createPrescription(new Prescription(prescriptionId, patientId, doctorId, nameOfMedicine, doseMg, numberOfTablets, dailyDose, explanation));
        doctorPrescriptionViewMessageLabel.setText("Prescription is saved!");
    }//GEN-LAST:event_doctorPrescriptionViewSaveButtonActionPerformed

    private void doctorPrescriptionViewUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewUpdateButtonActionPerformed
        doctorPrescriptionViewMessageLabel.setText("");
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = new java.sql.Date(doctorPrescriptionViewPatientsBirthdateDateChooser.getDate().getTime());
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        int doseMg = Integer.parseInt(doctorPrescriptionViewDoseTextField.getText());
        int numberOfTablets = Integer.parseInt(doctorPrescriptionViewNumberOfTabletsTextField.getText());
        int dailyDose = Integer.parseInt(doctorPrescriptionViewDailyDoseTextField.getText());
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();
        String doctorId = doctorPrescriptionViewDoctorIdTextField.getText();

        service.updatePrescription(new Prescription(prescriptionId, patientId, doctorId, nameOfMedicine, doseMg, numberOfTablets, dailyDose, explanation));
        doctorPrescriptionViewMessageLabel.setText("Prescription is updated!");
    }//GEN-LAST:event_doctorPrescriptionViewUpdateButtonActionPerformed

    private void doctorPrescriptionViewPrescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrescriptionButtonActionPerformed
        String patientId = doctorPrescriptionViewPatientsIdTextField.getText();
        String patientName = doctorPrescriptionViewPatientsNameTextField.getText();
        String patientSurname = doctorPrescriptionViewPatientsSurnameTextField.getText();
        Date patientBirthdate = new java.sql.Date(doctorPrescriptionViewPatientsBirthdateDateChooser.getDate().getTime());
        String patientGender = doctorPrescriptionViewPatientsGenderComboBox.getSelectedItem().toString();
        String nameOfMedicine = doctorPrescriptionViewMedicineNameTextField.getText();
        String doseMg = doctorPrescriptionViewDoseTextField.getText();
        String numberOfTablets = doctorPrescriptionViewNumberOfTabletsTextField.getText();
        String dailyDose = doctorPrescriptionViewDailyDoseTextField.getText();
        String prescriptionId = doctorPrescriptionViewPrescriptionIdTextField.getText();
        String explanation = doctorPrescriptionViewExplanationTextField.getText();
        String doctorId = doctorPrescriptionViewDoctorIdTextField.getText();

        doctorsPrescriptionViewPrescriptionTextArea.setText("");
        doctorsPrescriptionViewPrescriptionTextArea.append("\t\n\tHospital Management System\n"
                + "\nPatient ID:\t\t" + patientId
                + "\nPatient Name:\t\t" + patientName + " " + patientSurname
                + "\nGender:\t\t" + patientGender
                + "\nDate of Birth:\t\t" + patientBirthdate
                + "\n\nPrescription ID:\t\t" + prescriptionId
                + "\nDoctor ID:\t\t" + doctorId
                + "\nMedicine Name:\t" + nameOfMedicine
                + "\nDose (mg):\t\t" + doseMg
                + "\nNumber of Tablets:\t" + numberOfTablets
                + "\nDaily Dose:\t\t" + dailyDose
                + "\nExplanation:\t\t" + explanation);

    }//GEN-LAST:event_doctorPrescriptionViewPrescriptionButtonActionPerformed

    private void doctorPrescriptionViewPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrintButtonActionPerformed
        try {
            doctorsPrescriptionViewPrescriptionTextArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(DoctorsPrescriptionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doctorPrescriptionViewPrintButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doctorPrescriptionViewAnamnesisLabel;
    private javax.swing.JTextField doctorPrescriptionViewAnamnesisTextField;
    private javax.swing.JLabel doctorPrescriptionViewDailyDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDailyDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewDoctorIdLabel;
    private javax.swing.JTextField doctorPrescriptionViewDoctorIdTextField;
    private javax.swing.JLabel doctorPrescriptionViewDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewExplanationLabel;
    private javax.swing.JTextField doctorPrescriptionViewExplanationTextField;
    private javax.swing.JLabel doctorPrescriptionViewMedicineNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewMedicineNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewMessageLabel;
    private javax.swing.JLabel doctorPrescriptionViewNumberOfTabletsLabel;
    private javax.swing.JTextField doctorPrescriptionViewNumberOfTabletsTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientIdLabel;
    private com.toedter.calendar.JDateChooser doctorPrescriptionViewPatientsBirthdateDateChooser;
    private javax.swing.JLabel doctorPrescriptionViewPatientsBirthdateLabel;
    private javax.swing.JComboBox<String> doctorPrescriptionViewPatientsGenderComboBox;
    private javax.swing.JLabel doctorPrescriptionViewPatientsGenderLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsIdTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsSurnameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsSurnameTextField;
    private javax.swing.JButton doctorPrescriptionViewPrescriptionButton;
    private javax.swing.JLabel doctorPrescriptionViewPrescriptionIdLabel;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionIdTextField;
    private javax.swing.JPanel doctorPrescriptionViewPrescriptionPane;
    private javax.swing.JButton doctorPrescriptionViewPrintButton;
    private javax.swing.JButton doctorPrescriptionViewSaveButton;
    private javax.swing.JButton doctorPrescriptionViewUpdateButton;
    private javax.swing.JTextArea doctorsPrescriptionViewPrescriptionTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private String lastId() {
        String prescriptionId = service.lastPrescriptionId();

        int idIncremented = Integer.parseInt(prescriptionId.substring(3)) + 1;

        prescriptionId = "PRE" + String.format("%03d", idIncremented);

        return prescriptionId;
    }
}
