/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.view.doctor;

import com.hms.view.receptionist.*;
import com.hms.view.admin.*;

/**
 *
 * @author domin
 */
public class DoctorPrescriptionView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminDoctorsView
     */
    public DoctorPrescriptionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorPrescriptionViewMedicineNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewMedicineNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDailyDoseTextField = new javax.swing.JTextField();
        doctorPrescriptionViewDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewNumberOfTabletsLabel = new javax.swing.JLabel();
        doctorPrescriptionViewDailyDoseLabel = new javax.swing.JLabel();
        doctorPrescriptionViewNumberOfTabletsTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsNameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsNameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsSurnameTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPatientsSurnameLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsGenderLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsGenderComboBox = new javax.swing.JComboBox<>();
        doctorPrescriptionViewPatientsBirthdateLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPatientsBirthdateTextField = new javax.swing.JTextField();
        doctorPrescriptionViewExplanationLabel = new javax.swing.JLabel();
        doctorPrescriptionViewExplanationTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionPane = new javax.swing.JPanel();
        doctorPrescriptionViewSaveButton = new javax.swing.JButton();
        doctorPrescriptionViewPrintButton = new javax.swing.JButton();
        doctorPrescriptionViewClearButton = new javax.swing.JButton();
        doctorPrescriptionViewAnamnesisLabel = new javax.swing.JLabel();
        doctorPrescriptionViewAnamnesisTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionButton = new javax.swing.JButton();
        doctorPrescriptionViewUpdateButton = new javax.swing.JButton();
        doctorPrescriptionViewPrescriptionIdLabel = new javax.swing.JLabel();
        doctorPrescriptionViewPrescriptionIdTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionSearchTextField = new javax.swing.JTextField();
        doctorPrescriptionViewPrescriptionSearchLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Prescription");

        doctorPrescriptionViewMedicineNameLabel.setText("Name of Medicine   :");

        doctorPrescriptionViewDoseLabel.setText("Dose (mg)              :");

        doctorPrescriptionViewNumberOfTabletsLabel.setText("Number of Tablets :");

        doctorPrescriptionViewDailyDoseLabel.setText("Daily Dose              :");

        doctorPrescriptionViewPatientIdLabel.setText("Patient ID               :");

        doctorPrescriptionViewPatientsNameLabel.setText("Name                      :");

        doctorPrescriptionViewPatientsSurnameLabel.setText("Surname                 :");

        doctorPrescriptionViewPatientsGenderLabel.setText("Gender                   :");

        doctorPrescriptionViewPatientsGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        doctorPrescriptionViewPatientsBirthdateLabel.setText("Birthdate                :");

        doctorPrescriptionViewPatientsBirthdateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPatientsBirthdateTextFieldActionPerformed(evt);
            }
        });

        doctorPrescriptionViewExplanationLabel.setText("Explanation            :");

        doctorPrescriptionViewPrescriptionPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout doctorPrescriptionViewPrescriptionPaneLayout = new javax.swing.GroupLayout(doctorPrescriptionViewPrescriptionPane);
        doctorPrescriptionViewPrescriptionPane.setLayout(doctorPrescriptionViewPrescriptionPaneLayout);
        doctorPrescriptionViewPrescriptionPaneLayout.setHorizontalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        doctorPrescriptionViewPrescriptionPaneLayout.setVerticalGroup(
            doctorPrescriptionViewPrescriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        doctorPrescriptionViewSaveButton.setText("Save");

        doctorPrescriptionViewPrintButton.setText("Print");

        doctorPrescriptionViewClearButton.setText("Clear");

        doctorPrescriptionViewAnamnesisLabel.setText("Anamnesis             :");

        doctorPrescriptionViewPrescriptionButton.setText("Prescription");

        doctorPrescriptionViewUpdateButton.setText("Update");
        doctorPrescriptionViewUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewUpdateButtonActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrescriptionIdLabel.setText("Prescription ID       :");

        doctorPrescriptionViewPrescriptionIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrescriptionIdTextFieldActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrescriptionSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed(evt);
            }
        });

        doctorPrescriptionViewPrescriptionSearchLabel.setText("Search Previous Prescription By Prescription ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctorPrescriptionViewPrescriptionSearchTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewAnamnesisTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(doctorPrescriptionViewSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doctorPrescriptionViewUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doctorPrescriptionViewClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doctorPrescriptionViewPrescriptionButton)
                                .addGap(10, 10, 10)
                                .addComponent(doctorPrescriptionViewPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(doctorPrescriptionViewPatientsSurnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorPrescriptionViewPatientsNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorPrescriptionViewPatientIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(doctorPrescriptionViewPatientsSurnameTextField)
                                        .addComponent(doctorPrescriptionViewPatientsNameTextField)
                                        .addComponent(doctorPrescriptionViewPatientsIdTextField)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(doctorPrescriptionViewPatientsBirthdateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(doctorPrescriptionViewPatientsGenderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorPrescriptionViewAnamnesisLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(doctorPrescriptionViewPatientsBirthdateTextField)
                                        .addComponent(doctorPrescriptionViewPatientsGenderComboBox, 0, 186, Short.MAX_VALUE))))
                            .addComponent(doctorPrescriptionViewPrescriptionSearchLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDailyDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewMedicineNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewDoseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPrescriptionViewMedicineNameTextField)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(doctorPrescriptionViewPrescriptionIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(doctorPrescriptionViewPrescriptionIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addComponent(doctorPrescriptionViewExplanationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doctorPrescriptionViewExplanationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewMedicineNameLabel)
                            .addComponent(doctorPrescriptionViewMedicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewDoseLabel)
                            .addComponent(doctorPrescriptionViewDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsLabel)
                            .addComponent(doctorPrescriptionViewNumberOfTabletsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewDailyDoseLabel)
                            .addComponent(doctorPrescriptionViewDailyDoseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPrescriptionIdLabel)
                            .addComponent(doctorPrescriptionViewPrescriptionIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(doctorPrescriptionViewExplanationLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientIdLabel)
                            .addComponent(doctorPrescriptionViewPatientsIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsNameLabel)
                            .addComponent(doctorPrescriptionViewPatientsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsSurnameLabel)
                            .addComponent(doctorPrescriptionViewPatientsSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateLabel)
                            .addComponent(doctorPrescriptionViewPatientsBirthdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPatientsGenderLabel)
                            .addComponent(doctorPrescriptionViewPatientsGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorPrescriptionViewAnamnesisLabel)
                    .addComponent(doctorPrescriptionViewExplanationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorPrescriptionViewAnamnesisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(doctorPrescriptionViewPrescriptionSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorPrescriptionViewPrescriptionSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewSaveButton)
                            .addComponent(doctorPrescriptionViewUpdateButton)
                            .addComponent(doctorPrescriptionViewClearButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorPrescriptionViewPrescriptionButton)
                            .addComponent(doctorPrescriptionViewPrintButton)))
                    .addComponent(doctorPrescriptionViewPrescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorPrescriptionViewPatientsBirthdateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPatientsBirthdateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorPrescriptionViewPatientsBirthdateTextFieldActionPerformed

    private void doctorPrescriptionViewUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorPrescriptionViewUpdateButtonActionPerformed

    private void doctorPrescriptionViewPrescriptionIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrescriptionIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorPrescriptionViewPrescriptionIdTextFieldActionPerformed

    private void doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorPrescriptionViewPrescriptionSearchTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doctorPrescriptionViewAnamnesisLabel;
    private javax.swing.JTextField doctorPrescriptionViewAnamnesisTextField;
    private javax.swing.JButton doctorPrescriptionViewClearButton;
    private javax.swing.JLabel doctorPrescriptionViewDailyDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDailyDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewDoseLabel;
    private javax.swing.JTextField doctorPrescriptionViewDoseTextField;
    private javax.swing.JLabel doctorPrescriptionViewExplanationLabel;
    private javax.swing.JTextField doctorPrescriptionViewExplanationTextField;
    private javax.swing.JLabel doctorPrescriptionViewMedicineNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewMedicineNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewNumberOfTabletsLabel;
    private javax.swing.JTextField doctorPrescriptionViewNumberOfTabletsTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientIdLabel;
    private javax.swing.JLabel doctorPrescriptionViewPatientsBirthdateLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsBirthdateTextField;
    private javax.swing.JComboBox<String> doctorPrescriptionViewPatientsGenderComboBox;
    private javax.swing.JLabel doctorPrescriptionViewPatientsGenderLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsIdTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsNameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsNameTextField;
    private javax.swing.JLabel doctorPrescriptionViewPatientsSurnameLabel;
    private javax.swing.JTextField doctorPrescriptionViewPatientsSurnameTextField;
    private javax.swing.JButton doctorPrescriptionViewPrescriptionButton;
    private javax.swing.JLabel doctorPrescriptionViewPrescriptionIdLabel;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionIdTextField;
    private javax.swing.JPanel doctorPrescriptionViewPrescriptionPane;
    private javax.swing.JLabel doctorPrescriptionViewPrescriptionSearchLabel;
    private javax.swing.JTextField doctorPrescriptionViewPrescriptionSearchTextField;
    private javax.swing.JButton doctorPrescriptionViewPrintButton;
    private javax.swing.JButton doctorPrescriptionViewSaveButton;
    private javax.swing.JButton doctorPrescriptionViewUpdateButton;
    // End of variables declaration//GEN-END:variables
}
