/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hms.view.doctor;

import com.hms.view.receptionist.*;

/**
 *
 * @author domin
 */
public class HMSDoctorMainView extends javax.swing.JFrame {

    /**
     * Creates new form HMSReceptionistMainView
     */
    public HMSDoctorMainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorMenuBar = new javax.swing.JMenuBar();
        doctorFileMenu = new javax.swing.JMenu();
        doctorFileMenuItemLogOut = new javax.swing.JMenuItem();
        doctorFileMenuItemExit = new javax.swing.JMenuItem();
        doctorOperationsMenu = new javax.swing.JMenu();
        doctorOperationsMenuItemAppointments = new javax.swing.JMenuItem();
        doctorOperationsMenuItemDoctors = new javax.swing.JMenuItem();
        doctorOperationsMenuItemPatients = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doctorFileMenu.setText("File");

        doctorFileMenuItemLogOut.setText("Log Out");
        doctorFileMenu.add(doctorFileMenuItemLogOut);

        doctorFileMenuItemExit.setText("Exit");
        doctorFileMenu.add(doctorFileMenuItemExit);

        doctorMenuBar.add(doctorFileMenu);

        doctorOperationsMenu.setText("Operations");

        doctorOperationsMenuItemAppointments.setText("Appointments");
        doctorOperationsMenu.add(doctorOperationsMenuItemAppointments);

        doctorOperationsMenuItemDoctors.setText("Doctors");
        doctorOperationsMenu.add(doctorOperationsMenuItemDoctors);

        doctorOperationsMenuItemPatients.setText("Patients");
        doctorOperationsMenu.add(doctorOperationsMenuItemPatients);

        doctorMenuBar.add(doctorOperationsMenu);

        setJMenuBar(doctorMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMSDoctorMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu doctorFileMenu;
    private javax.swing.JMenuItem doctorFileMenuItemExit;
    private javax.swing.JMenuItem doctorFileMenuItemLogOut;
    private javax.swing.JMenuBar doctorMenuBar;
    private javax.swing.JMenu doctorOperationsMenu;
    private javax.swing.JMenuItem doctorOperationsMenuItemAppointments;
    private javax.swing.JMenuItem doctorOperationsMenuItemDoctors;
    private javax.swing.JMenuItem doctorOperationsMenuItemPatients;
    // End of variables declaration//GEN-END:variables
}
