
package com.hms.view.doctor;

import com.hms.view.Login;

public class HMSDoctorMainView extends javax.swing.JFrame {

    public HMSDoctorMainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorDesktopPane = new javax.swing.JDesktopPane();
        doctorMenuBar = new javax.swing.JMenuBar();
        doctorFileMenu = new javax.swing.JMenu();
        doctorFileMenuItemLogOut = new javax.swing.JMenuItem();
        doctorFileMenuItemExit = new javax.swing.JMenuItem();
        doctorOperationsMenu = new javax.swing.JMenu();
        doctorOperationsMenuItemAppointments = new javax.swing.JMenuItem();
        doctorOperationsMenuItemDoctors = new javax.swing.JMenuItem();
        doctorOperationsMenuItemPatients = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout doctorDesktopPaneLayout = new javax.swing.GroupLayout(doctorDesktopPane);
        doctorDesktopPane.setLayout(doctorDesktopPaneLayout);
        doctorDesktopPaneLayout.setHorizontalGroup(
            doctorDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        doctorDesktopPaneLayout.setVerticalGroup(
            doctorDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        doctorFileMenu.setText("File");

        doctorFileMenuItemLogOut.setText("Log Out");
        doctorFileMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorFileMenuItemLogOutActionPerformed(evt);
            }
        });
        doctorFileMenu.add(doctorFileMenuItemLogOut);

        doctorFileMenuItemExit.setText("Exit");
        doctorFileMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorFileMenuItemExitActionPerformed(evt);
            }
        });
        doctorFileMenu.add(doctorFileMenuItemExit);

        doctorMenuBar.add(doctorFileMenu);

        doctorOperationsMenu.setText("Operations");

        doctorOperationsMenuItemAppointments.setText("Appointments");
        doctorOperationsMenuItemAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorOperationsMenuItemAppointmentsActionPerformed(evt);
            }
        });
        doctorOperationsMenu.add(doctorOperationsMenuItemAppointments);

        doctorOperationsMenuItemDoctors.setText("Doctors");
        doctorOperationsMenuItemDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorOperationsMenuItemDoctorsActionPerformed(evt);
            }
        });
        doctorOperationsMenu.add(doctorOperationsMenuItemDoctors);

        doctorOperationsMenuItemPatients.setText("Patients");
        doctorOperationsMenuItemPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorOperationsMenuItemPatientsActionPerformed(evt);
            }
        });
        doctorOperationsMenu.add(doctorOperationsMenuItemPatients);

        doctorMenuBar.add(doctorOperationsMenu);

        setJMenuBar(doctorMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doctorFileMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFileMenuItemLogOutActionPerformed
        Login login = new Login();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_doctorFileMenuItemLogOutActionPerformed

    private void doctorFileMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorFileMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_doctorFileMenuItemExitActionPerformed

    private void doctorOperationsMenuItemAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorOperationsMenuItemAppointmentsActionPerformed
        DoctorAppointmentView doctorAppointmentView = new DoctorAppointmentView();
        doctorDesktopPane.add(doctorAppointmentView).setVisible(true);
    }//GEN-LAST:event_doctorOperationsMenuItemAppointmentsActionPerformed

    private void doctorOperationsMenuItemDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorOperationsMenuItemDoctorsActionPerformed
        DoctorDoctorsView doctorDoctorsView = new DoctorDoctorsView();
        doctorDesktopPane.add(doctorDoctorsView).setVisible(true);
    }//GEN-LAST:event_doctorOperationsMenuItemDoctorsActionPerformed

    private void doctorOperationsMenuItemPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorOperationsMenuItemPatientsActionPerformed
        DoctorPatientsView doctorPatientsView = new DoctorPatientsView();
        doctorDesktopPane.add(doctorPatientsView).setVisible(true);
    }//GEN-LAST:event_doctorOperationsMenuItemPatientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMSDoctorMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMSDoctorMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane doctorDesktopPane;
    private javax.swing.JMenu doctorFileMenu;
    private javax.swing.JMenuItem doctorFileMenuItemExit;
    private javax.swing.JMenuItem doctorFileMenuItemLogOut;
    private javax.swing.JMenuBar doctorMenuBar;
    private javax.swing.JMenu doctorOperationsMenu;
    private javax.swing.JMenuItem doctorOperationsMenuItemAppointments;
    private javax.swing.JMenuItem doctorOperationsMenuItemDoctors;
    private javax.swing.JMenuItem doctorOperationsMenuItemPatients;
    // End of variables declaration//GEN-END:variables
}
